### ISSUE TITLE
引入太多第三方类报错

### ISSUE THREAD

**Issue by hsiunien** [rongcloud/RTC-Quick-Start-Android#1]
建议用原生最基础的方式展示RTC的功能和框架
不要引入第三方SDK，如Bugly。
不要提交local.properties中的内容
不要把第三方app key 放在demo中。

**Comment by hsiunien** [comment]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/cn.rongcloud.rtc-7Tdbg1logUuUeR1P0ZrZDg==/base.apk"],nativeLibraryDirectories=[/data/app/cn.rongcloud.rtc-7Tdbg1logUuUeR1P0ZrZDg==/lib/arm64, /system/lib64, /hw_product/lib64, /system/product/lib64]]] couldn't find "lib_RongRTC_so.so"

**Comment by hsiunien** [comment]
sorry 说的是隔壁sealrtc-android 那个工程

**Comment by HuichaoLi** [comment]
感谢反馈，SealRTC-Android是一个带有多种功能的demo源码项目，包括自定义音频/视频，美颜，白板等功能，所以会用到一些第三方SDK。
