### ISSUE TITLE
RongIMClient.connect(token, new RongIMClient.ConnectCallback()  什么回调都没有

### ISSUE THREAD

**Issue by hsiunien** [rongcloud/RTC-Quick-Start-Android#2]
06-01 00:14:21.346 2220-2301/cn.rongcloud.sealcall E/EGL_emulation: tid 2301: eglSurfaceAttrib(1033): error 0x3009 (EGL_BAD_MATCH)
06-01 00:14:21.346 2220-2301/cn.rongcloud.sealcall W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xa03fe200, error=EGL_BAD_MATCH
06-01 00:14:22.408 2220-2220/cn.rongcloud.sealcall D/Activity: on create, cpu abi: x86, brand: HUAWEI
06-01 00:14:22.479 2220-2301/cn.rongcloud.sealcall E/EGL_emulation: tid 2301: eglSurfaceAttrib(1033): error 0x3009 (EGL_BAD_MATCH)
06-01 00:14:22.479 2220-2301/cn.rongcloud.sealcall W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xa02a8020, error=EGL_BAD_MATCH
06-01 00:14:22.571 2220-2301/cn.rongcloud.sealcall D/OpenGLRenderer: endAllStagingAnimators on 0xb3b6dd00 (RippleDrawable) with handle 0xa037f060
06-01 00:14:22.906 2220-2220/cn.rongcloud.sealcall I/RongLog: [RongLog][ RongIMClient ] saveInstance
06-01 00:14:28.444 2220-2220/cn.rongcloud.sealcall I/[RC:A-connect-T]: {"ptid":"2220-1*","token":"xxxxxxxxxx"}
06-01 00:14:28.445 2220-2220/cn.rongcloud.sealcall I/[RC:L-connect-T]: {"ptid":"2220-1*","sequences":0}
06-01 00:14:28.445 2220-2220/cn.rongcloud.sealcall W/RongLog: [RongLog][ RongIMClient ] Current state is connecting, cache callback: io.rong.imlib.RongIMClient$3@85b06fb
06-01 00:14:28.445 2220-2220/cn.rongcloud.sealcall I/Choreographer: Skipped 64 frames!  The application may be doing too much work on its main thread.

**Comment by HuichaoLi** [comment]
当前项目里引用的SDK版本比较老了，这个版本的SDK有一个低概率错误。卸载掉APK重装一次，就可以了。
另外，需要运行SealRTC项目。SealCall demo已经不再维护。
